<?php

declare(strict_types=1);

/**
 * Builds database/hosting-import.sql = schema.sql + seed.sql without the
 * "CREATE DATABASE" / "USE bhsystem" lines, for web hosts (InfinityFree,
 * Hostinger ...) that give you a ready database with their own name and
 * do not allow creating databases.
 *
 *   php setup/make-hosting-sql.php
 *
 * Import the result in the host's phpMyAdmin after selecting your database.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$dir = __DIR__ . '/../database';
$strip = static fn (string $sql): string => preg_replace('/^\s*(CREATE DATABASE\b[^;]*;|USE\s+`?bhsystem`?\s*;)\s*$/mi', '', $sql);

$out = "-- ============================================================================\n"
    . "-- Boarding House Rental System - IMPORT FILE FOR WEB HOSTING\n"
    . "-- Generated by setup/make-hosting-sql.php from schema.sql + seed.sql.\n"
    . "-- In the host's phpMyAdmin: select YOUR database first, then Import this file.\n"
    . "-- It creates all tables and the demo accounts. Change the demo passwords after!\n"
    . "-- ============================================================================\n\n"
    . $strip((string) file_get_contents($dir . '/schema.sql'))
    . "\n\n-- ---------------------------------------------------------------- demo data\n\n"
    . $strip((string) file_get_contents($dir . '/seed.sql'));

file_put_contents($dir . '/hosting-import.sql', $out);
echo 'Created database/hosting-import.sql (' . round(strlen($out) / 1024) . " KB)\n";
