<?php
$rooms = [
    [
        'id' => 1,
        'title' => 'Cozy Student Room',
        'rent' => 3500,
        'type' => 'Shared Room',
        'availability' => '2 rooms left',
        'occupants' => 2,
        'distance' => '1.2 km',
        'barangay' => 'Brgy. Luna',
        'city' => 'Surigao City',
        'province' => 'Surigao del Norte',
        'zip' => '8400',
        'rating' => 4.8,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
        'badge' => 'New Listing',
        'featured' => true,
        'deposit' => 7000,
        'advance' => 3500,
        'size' => '12 sqm',
        'capacity' => '2 students',
        'roomStatus' => 'Available Now',
        'description' => 'Bright and well-kept shared room ideal for students who want a calm place near the university. The property includes a study corner, reliable water, and indoor lounge access.',
        'amenities' => ['WiFi', 'Air Conditioning', 'Study Table', 'Private Bathroom', 'Kitchen', 'Laundry Area', 'CCTV', 'Water Included'],
        'address' => 'Block 4, Lot 15, Brgy. Luna, Surigao City',
        'landlord' => [
            'name' => 'Maria Santos',
            'verified' => true,
            'contact' => '+63 917 123 4567',
            'email' => 'maria.santos@example.com',
            'years' => 7,
            'listedRooms' => 12,
            'responseTime' => 'Under 1 hour',
            'rating' => 4.9,
        ],
        'rules' => ['No smoking', 'Quiet hours from 10 PM to 6 AM', 'Visitors allowed until 9 PM', 'Monthly dues due every 5th day'],
        'nearby' => [
            ['name' => 'University', 'distance' => '800m'],
            ['name' => 'Hospital', 'distance' => '1.4km'],
            ['name' => 'Pharmacy', 'distance' => '600m'],
            ['name' => 'Laundry Shop', 'distance' => '300m'],
        ],
        'reviews' => [
            ['name' => 'Dianne', 'rating' => 5, 'comment' => 'Very clean and close to school. The landlord is responsive.', 'date' => '2 days ago'],
            ['name' => 'Jhon', 'rating' => 4, 'comment' => 'Safe neighborhood and good amenities for focused studying.', 'date' => '1 week ago'],
        ],
        'tags' => ['WiFi', 'Air Conditioned', 'Private CR', 'Near School'],
    ],
    [
        'id' => 2,
        'title' => 'Modern Studio Apartment',
        'rent' => 4800,
        'type' => 'Solo Room',
        'availability' => '1 room left',
        'occupants' => 1,
        'distance' => '2.3 km',
        'barangay' => 'Brgy. Canlanipa',
        'city' => 'Surigao City',
        'province' => 'Surigao del Norte',
        'zip' => '8400',
        'rating' => 4.9,
        'image' => 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
        'badge' => 'Popular',
        'featured' => true,
        'deposit' => 10000,
        'advance' => 4800,
        'size' => '15 sqm',
        'capacity' => '1 student',
        'roomStatus' => 'Booked Soon',
        'description' => 'A quiet private studio with a compact kitchenette, plenty of air flow, and a dedicated study space. Perfect for focused learning and privacy.',
        'amenities' => ['WiFi', 'Air Conditioning', 'Bed', 'Cabinet', 'Study Table', 'Private Bathroom', 'Balcony', 'Parking'],
        'address' => 'Lot 22, Canlanipa Street, Surigao City',
        'landlord' => [
            'name' => 'Renato Cruz',
            'verified' => true,
            'contact' => '+63 918 654 2211',
            'email' => 'renato.cruz@example.com',
            'years' => 5,
            'listedRooms' => 8,
            'responseTime' => '30 mins',
            'rating' => 4.8,
        ],
        'rules' => ['No smoking', 'No pets', 'Visitors by appointment only', 'Rent due on the 1st week of each month'],
        'nearby' => [
            ['name' => 'Convenience Store', 'distance' => '500m'],
            ['name' => 'ATM', 'distance' => '900m'],
            ['name' => 'Jeepney Terminal', 'distance' => '1.1km'],
            ['name' => 'Restaurants', 'distance' => '700m'],
        ],
        'reviews' => [
            ['name' => 'Kyla', 'rating' => 5, 'comment' => 'Fantastic layout and very comfortable for study sessions.', 'date' => '3 days ago'],
        ],
        'tags' => ['WiFi', 'Air Conditioned', 'Parking', 'Private CR'],
    ],
    [
        'id' => 3,
        'title' => 'Dormitory Room',
        'rent' => 2800,
        'type' => 'Dormitory',
        'availability' => '4 rooms left',
        'occupants' => 4,
        'distance' => '700m',
        'barangay' => 'Brgy. Washington',
        'city' => 'Surigao City',
        'province' => 'Surigao del Norte',
        'zip' => '8400',
        'rating' => 4.7,
        'image' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
        'badge' => 'Budget Friendly',
        'featured' => false,
        'deposit' => 5600,
        'advance' => 2800,
        'size' => '10 sqm',
        'capacity' => '4 students',
        'roomStatus' => 'Available Now',
        'description' => 'A practical dorm-type setup with shared lounge and scheduled cleaning, ideal for students who want affordability without compromising safety.',
        'amenities' => ['WiFi', 'Electric Fan', 'Bed', 'Cabinet', 'Shared Bathroom', 'Kitchen', 'Laundry Area', 'CCTV'],
        'address' => 'Mapawa Road, Brgy. Washington, Surigao City',
        'landlord' => [
            'name' => 'Liza Torres',
            'verified' => true,
            'contact' => '+63 999 112 3344',
            'email' => 'liza.torres@example.com',
            'years' => 4,
            'listedRooms' => 6,
            'responseTime' => '2 hours',
            'rating' => 4.7,
        ],
        'rules' => ['Quiet hours', 'Curfew at 10 PM', 'No visitors during exam week', 'Monthly dues due every 10th'],
        'nearby' => [
            ['name' => 'University', 'distance' => '500m'],
            ['name' => 'Pharmacy', 'distance' => '350m'],
            ['name' => 'Convenience Store', 'distance' => '250m'],
            ['name' => 'Restaurants', 'distance' => '400m'],
        ],
        'reviews' => [
            ['name' => 'Mica', 'rating' => 4, 'comment' => 'Good value for money and very accessible to school.', 'date' => '5 days ago'],
        ],
        'tags' => ['WiFi', 'Near School', 'Shared Bathroom', 'Budget'],
    ],
    [
        'id' => 4,
        'title' => 'Family Boarding House',
        'rent' => 4200,
        'type' => 'Mixed',
        'availability' => '3 rooms left',
        'occupants' => 3,
        'distance' => '1.7 km',
        'barangay' => 'Brgy. San Juan',
        'city' => 'Surigao City',
        'province' => 'Surigao del Norte',
        'zip' => '8400',
        'rating' => 4.8,
        'image' => 'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80',
        'badge' => 'Comfort',
        'featured' => false,
        'deposit' => 8400,
        'advance' => 4200,
        'size' => '14 sqm',
        'capacity' => '3 students',
        'roomStatus' => 'Available Now',
        'description' => 'A welcoming mixed boarding house managed by a family, offering a secure and friendly environment for student renters.',
        'amenities' => ['WiFi', 'Air Conditioning', 'Electric Fan', 'Bed', 'Cabinet', 'Study Table', 'Shared Bathroom', 'Parking'],
        'address' => 'San Juan Road, Brgy. San Juan, Surigao City',
        'landlord' => [
            'name' => 'Alicia Buenaventura',
            'verified' => true,
            'contact' => '+63 916 737 9988',
            'email' => 'alicia.b@example.com',
            'years' => 9,
            'listedRooms' => 10,
            'responseTime' => '1 hour',
            'rating' => 4.9,
        ],
        'rules' => ['No pets', 'No smoking inside rooms', 'Guests until 8 PM', 'Payments every 15th'],
        'nearby' => [
            ['name' => 'University', 'distance' => '1.2km'],
            ['name' => 'Laundry Shop', 'distance' => '400m'],
            ['name' => 'Restaurant', 'distance' => '600m'],
            ['name' => 'ATM', 'distance' => '800m'],
        ],
        'reviews' => [
            ['name' => 'Renz', 'rating' => 5, 'comment' => 'Friendly environment and very convenient for commuting.', 'date' => '6 days ago'],
        ],
        'tags' => ['WiFi', 'Parking', 'Mixed', 'Near School'],
    ],
];

function findRoomById($roomId)
{
    global $rooms;
    foreach ($rooms as $room) {
        if ((int) $room['id'] === (int) $roomId) {
            return $room;
        }
    }

    return null;
}
?>
